import { HEADER_BLOCK_SCHEMA, SOCIAL_PLATFORMS } from './blocks';
import { AI_THEME, DOODLE_SKETCH_THEME, HANDRAWN_CREAM_THEME, MINIMAL_THEME, RETRO_WIN95_THEME, RISOGRAPH_PRINT_THEME } from './themes';

export const EDITOR_REGISTRY = {
  themes: [MINIMAL_THEME, DOODLE_SKETCH_THEME, RETRO_WIN95_THEME, RISOGRAPH_PRINT_THEME, HANDRAWN_CREAM_THEME, AI_THEME],
  blocks: [HEADER_BLOCK_SCHEMA],
  socialPlatforms: SOCIAL_PLATFORMS,
};
